export const USER_LOGIN = "USER_LOGIN_ACTION";
export const USER_LOGOUT = "USER_LOGOUT_ACTION";

export const NEW_NOTIFICATION = "NEW_NOTIFICATION";
export const CANCEL_NOTIFICATION = "CANCEL_NOTIFICATION";